merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/',views.band_list, name='band-list'),
    path('about-us/',views.about,name="about"),
    path('listings/',views.annonce_list, name='annonce-list'),
    path('contact/',views.contact,name='contact'),

    #url pour le lien cliqué
    path('bands/<int:id>/',views.band_detail,name='band-detail'),
    path('listings/<int:id>/',views.annonce_detail, name='annonce-detail'),
    path('listings/add/',views.annonce_create, name='annonce-create'),

    path('bands/add/',views.band_create,name='band-create'),

    #url de page de redirection
    path('email-sent/',views.confirmation,name="redirect"),

    #Mise à jour d'un Band et d'une annonce
    path('bands/<int:id>/change/',views.update_band,name="band-update"),
    path('listings/<int:id>/change/',views.update_annonce, name='annonce-update'),

    #suppression de la Base de données
    path('bands/<int:id>/delete/',views.delete_band,name='band-delete'),
    path('listings/<int:id>/delete/',views.delete_annonce,name='annonce-delete'),

]   

merchex/listings/models.py
from django.db import models,migrations
from datetime import datetime
from django.core.validators import MinValueValidator,MaxValueValidator

# CREATION D'UN MODEL
class Band(models.Model):
    name=models.fields.CharField(max_length=100)
    genre=models.fields.CharField(max_length=50)
    biography=models.fields.CharField(max_length=1000)
    year_formed=models.fields.IntegerField(validators=[MinValueValidator(1900),MaxValueValidator(2022)])
    active=models.fields.BooleanField(default=True)
    official_homepage=models.fields.URLField(null=True,blank=True)
 

    #Creation de la classe genre
    class Genre(models.TextChoices):
        HIP_HOP='HH'
        SYNTH_POP='SP'
        ALTERNATIVE_ROCK='AR'
    genre=models.fields.CharField(choices=Genre.choices,max_length=5)

    def __str__(self):
        return f'{self.name}'
    

class Annonce(models.Model):
    title=models.fields.CharField(max_length=100)
    description=models.fields.CharField(max_length=1000)
    sold=models.fields.BooleanField(default=False)
    year=models.fields.IntegerField(null=True,blank=True)
    typeA=models.fields.CharField(max_length=50)

    
    #création de la classe Type
    class Type(models.TextChoices):
        disques='Records'
        vetements='Clothing'
        affiches='Posters'
        divers='Miscellaneous'
    typeA=models.fields.CharField(choices=Type.choices,max_length=50)
    band=models.ForeignKey(Band,null=True,on_delete=models.SET_NULL)


    def __str__(self):
        return f'{self.title}'
    
    

merchex/listings/forms.py
from django import forms
from listings.models import Band,Annonce

class ContactUsForm(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    message=forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
    class Meta:
        model=Band
        #fields='__all__'
        exclude=('active','official_homepage')

class ListingForm(forms.ModelForm):
    class Meta:
        model=Annonce
        fields='__all__'

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from listings.models import Band
from listings.models import Annonce
from listings.forms import ContactUsForm,BandForm,ListingForm
from django.core.mail import send_mail

#Module de Redirection de Mesage
from django.shortcuts import redirect

def band_list(request):
    bands=Band.objects.all()
    return render(request,'listings/band_list.html',
    {'first_band':bands})

def annonce_list(request):
    annonces=Annonce.objects.all()
    return render(request,'listings/annonce_list.html',
    {'listings':annonces})

def about(request):
    contenu='A propos. Nous adorons merch. Espert !!!'
    return render(request,'listings/about.html',
    {'contenu':contenu})


#Ici nous avons renvoyer l'objet form
def contact(request):
    if request.method=='POST':
        #creation d'une instance du formulaire et le remplir
        form=ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme"} via MerchEx Contact Us Form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['yaomariussodokin@gmail.com']
            )
            #Redirection
            return redirect('email-sent')

    else:
        #creation d'une instance de formulaire vide
        form=ContactUsForm()
    
    return render(request,'listings/contact.html',
    {'form': form})


#Vue pour la page des details
def band_detail(request,id):
    band=Band.objects.get(id=id)
    return render(request,
    'listings/band_detail.html',
    {'band':band})


def band_create(request):
    if request.method=='POST':
        form=BandForm(request.POST)

        #Verification de la validation des valeurs
        if form.is_valid():
            band=form.save()

            #redirection
            return redirect('band-detail',band.id)
    
    else:
        form=BandForm()

    return render(request,
        'listings/band_create.html',
        {'form':form})

#Vue d'Enregistrement d'une annonce
def annonce_create(request):
    if request.method=='POST':
        form=ListingForm(request.POST)
        
        if form.is_valid():
            annonce=form.save()

            #redirection
            return redirect('annonce-create',annonce.id)
    else:
        form=ListingForm()

    return render(request,
    'listings/annonce_create.html',
    {'form':form})


def annonce_detail(request,id):
    annonce=Annonce.objects.get(id=id)
    return render(request,
    'listings/annonce_detail.html',
    {'annonce':annonce})

#Vue pour la page de confirmation
def confirmation(request):
    return render(request,
    'listings/email_sent.html',
    {'confirmation': "Veuillez confirmer le nouvel envoi du formulaire !!!"})


#Mise à jour d'un groupe 
def update_band(request,id):
    band=Band.objects.get(id=id)

    if request.method=='POST':
        form=BandForm(request.POST,instance=band)
        if form.is_valid():
            form.save()

            return redirect('band-detail',band.id)
    else:
        #remplir le formulaire
        form=BandForm(instance=band)

    return render(request,
    'listings/band_update.html',
    {'form':form})


    #Mettre à jour une annonce
def update_annonce(request,id):
    annonce=Annonce.objects.get(id=id)

    if request.method=='POST':
        form=ListingForm(request.POST,instance=annonce)
        if form.is_valid():
            form.save()

            #redirection
            return redirect('annonce-detail',annonce.id)
    else:
        form=ListingForm(instance=annonce)
    
    return render(request,
                'listings/annonce_update.html',
                {'form':form})

#Vue de suppression
def delete_band(request,id):
    band=Band.objects.get(id=id)
    
    if request.method=='POST':
        band.delete()

        return redirect('band-list')
    return render(request,
    'listings/band_delete.html',
    {'band':band})


def delete_annonce(request,id):
    annonce=Annonce.objects.get(id=id)
    
    if request.method=='POST':
        annonce.delete()

        return redirect('annonce-list')
    return render(request,
    'listings/annonce_delete.html',
    {'annonce':annonce})

merchex/listings/templates/listings/about.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>ABOUT US</h1>
    <p>
       {{contenu}} 
       Une équipe très solide au travail.

    </p>
    {% endblock %}    

merchex/listings/templates/listings/annonce_create.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Enregistrement d'une nouvelle annonce </h1>

<form action="" method="POST">
    {% csrf_token %}

    {{form.as_p }}

    <input type="submit" value="Valider">
</form>
{% endblock %} 

merchex/listings/templates/listings/annonce_delete.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>SUPPRESSION D'UNE PUBLICITE</h1>
<h2>Voulez vous vraiment continuer a suppression de cette publicité ?  Annonce {{annonce.title}} !!</h2>
<form action="" method="POST">
    {% csrf_token %}
 
<input type="submit" value="Supprimer">
</form>
{% endblock %}

merchex/listings/templates/listings/annonce_detail.html
{% extends 'listings/base.html' %}

{% block content %}
 
<h2> {{annonce.title}} </h2>
<ul>
    <li>Description :{{ annonce.description}}</li>
    <li> A ETE SOLDE : {{annonce.sold | yesno}}</li>
     <li> ANNEE DE PUBLICATION : {{annonce.year}}</li>
    <li> TYPE D'ANNONCE : {{annonce.get_typeA_display}}</li>
    <li> GROUPE AUTEUR : {{annonce.band}}</li>
</ul>
<a href="{% url 'annonce-list' %}"> <button >RETOUR A LA LISTE DES ANNONCES</button></a>
<a href="{% url 'annonce-update'  annonce.id %}"> <button >Modifier</button></a>
<a href="{% url 'annonce-delete'  annonce.id %}"> <button >Supprimer</button></a>

{% endblock %}

merchex/listings/templates/listings/annonce_list.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>LISTE DES ANNONCES PUBLIEES </h1>
    <ul>
    {%for list in listings %}
    <li> <a href="{% url 'annonce-detail' list.id %}">{{list.title}}</a>
    <a href="{% url 'annonce-update' list.id %}">[Modifier]</a>
    <a href="{% url 'annonce-delete' list.id %}">[Supprimer]</a>

    </li>
    {% endfor %}

</ul>
<a href="{% url 'annonce-create' %}"> Créer une nouvelle annonce </a>
{% endblock %} 

merchex/listings/templates/listings/annonce_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>MIDE A JOUR D'UNE PUBLICITE</h1>
<form action="" method="POST">
    {% csrf_token %}
  {{form.as_p}}

<input type="submit" value="Enregistrer">
</form>
{% endblock %}

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Enregistrement d'un nouveau groupe </h1>

<form action="" method="POST">

{% csrf_token %}

{{form.as_p}}
<input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>SUPPRESSION D'UN GROUPE</h1>
<h2>Voulez vous vraiment continuer a suppression de ce groupe ?  Groupe {{band.name}} !!</h2>
<form action="" method="POST">
    {% csrf_token %}
 
<input type="submit" value="Supprimer">
</form>
{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2> {{band.name}}</h2>
<ul>
    <li> Genre : {{band.get_genre_display}}</li>
    <li>Formation : {{band.year_formed}}</li>
    <li> Actif : {{band.active | yesno}}</li>

    <!-- VERIFIONS SI LA PAGE OFFICIEL EXISTE-->
     { % if band.official_homepage  %}
    <li> Page d'Accueil Officiel :  <a href="{{band.official_homepage}}">{{band.official_homepage}}</a></li>
    {%  endif % }
</ul>

 <p> Biographie : {{band.biography}} </p>

 <a href="{% url 'band-list' %}"> <button >RETOUR A LA LISTE DES GROUPES</button></a>
 <a href="{% url 'band-update'  band.id %}"> <button >Editer</button></a>
 <a href="{% url 'band-delete'  band.id %}"> <button >Supprimer</button></a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
<!-- AJOUT DES BALISES DE GABARITS SUPPLEMENTAIRE -->

{% extends 'listings/base.html' %}

{% block content %}

    <h1>Groupes</h1>
    <p>Mes groupes spréférés sont :</p>
    <ul style="font-weight: bold;">
        {%for band in first_band %}
  <li> <a href="{% url 'band-detail' band.id %}">{{band.name}} </a>
    <a href="{% url 'band-update' band.id %}">[Editer] </a>
    <a href="{% url 'band-delete' band.id %}">[Suppimer] </a>

</li> 
         {% endfor %}
         Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore, obcaecati ipsum. Aspernatur saepe harum dolores sunt temporibus quasi expedita delectus iste. Maiores pariatur ab fuga possimus, cumque adipisci velit in?
    </ul>
    <a href="{% url 'band-create' %}">Créer un nouveau groupe</a>
    {% endblock %}    

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>MIDE A JOUR D'UN GROUPE</h1>
<form action="" method="POST">
    {% csrf_token %}
  {{form.as_p}}

<input type="submit" value="Enregistrer">
</form>
{% endblock %}

merchex/listings/templates/listings/base.html
<DOCTYPE html>
    {% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'listings/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Merchex</title>
</head>
<body>
    <nav>
        <a href="{% url  'band-list' %}">Groupes</a>
        <a href="{% url  'annonce-list' %}">Annonces</a>
        <a href="{% url  'contact' %}">Nous Contacter</a>
        <a href="{% url  'about' %}">A Propos</a>

   </nav>
    {% block content %}{% endblock %}
</body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

    <h1>Nous sommes là pour vous aider</h1>
    <form action="" method="POST" novalidate>
        {% csrf_token %}

        {{form.as_p}}
 <input type="submit" value="Envoyer">
    </form>
    <div style="display: inline-block;">
    <i class="fa-solid fa-phone"> 90500075 /94340400</i>  <br>
    <i class="fa fa-envelope" >yaomariussodokin@gmail.com</i><br>
   <i class="fa fa-facebook"> Sodokin Yao Marius</i><br>
    <i class="fa fa-whatsapp">90500075</i><br>
    <i class="fa fa-instagram" >Yao MArius SODOKIN</i><br>
    <i class="fa fa-linkedin"> sODOKIN mARIUS</i><br>
</div>

 {% endblock %}

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}
<h1>Confirmation Email</h1>

{% endblock %}